### ISSUE TITLE
Call to undefined method CellXXX::display() 

### ISSUE THREAD

**Issue by mnshankar** [Torann/laravel-4-cells#1]
Hi,
Thanks for this package. It fits my requirement very well.

I noticed this error right after installation.. "Call to undefined method CellDemo::display() "
Upon closer inspection of the source code, I realize that the cell controller is expected to have this function, and creating this function solves the issue.

I also noticed a stub for "public function run()" that was not really being used in the base controller, doing exactly what "display" does/is supposed to do. 
So, wondering if this is just a bug.. or does "run" have a bigger role (to be implemented later) to play in the cell life cycle?

**Comment by Torann** [comment]
Sorry, I just ran into the same thing. The controller template was missing the "display" method. The "run" method was renamed to "display" in the last release and wasn't updated in the template. 

All fixed, thanks for the heads up :-)
